# cmd: conda build . -c conda-forge
package:
    name: pac99
    version: "1.3.0"

source:
    path: .

requirements:
    build:
        - conda-forge::cmake=3.21.3
        - conda-forge::gfortran_linux-64=7.5.0
