version: 2
jobs:
    build-and-test:
        docker:
            - image: continuumio/miniconda3
        steps:
          - checkout
          - run:
              name: Create conda environment
              command: |
                  apt-get update --yes
                  apt-get install --yes build-essential
                  conda env create -f environment.yml
          - run:
              name: Build the code
              command: |
                  source activate pac99-env
                  bash debug/build.sh
          - run:
              name: Test the code
              command: |
                  source activate pac99-env
                  . debug/fake-install.sh
                  cd examples
                  cd ch4
                  bash run_pac99.sh
                  cd ..
                  cd co
                  bash run_pac99.sh
                  cd ..
                  cd h2
                  bash run_pac99.sh
                  cd ..
workflows:
    version: 2
    build-all:
        jobs:
            - build-and-test
